### YamlMime:AchievementDetail
achievementUid: learn-bizapps.sustainability-setup-environment.badge
metadata:
  title: 'Microsoft Badge: Set up your training environment was issued by Microsoft'
socialImageUrl: /learn/achievements/sustainability-setup-environment-social.png
