### YamlMime:AchievementDetail
achievementUid: learn-bizapps.power-bi-deployment-pipelines.badge
metadata:
  title: >-
    Microsoft Badge: Create and manage a Power BI deployment pipeline was issued
    by Microsoft
socialImageUrl: /training/achievements/power-bi-deployment-pipelines-social.png
