### YamlMime:AchievementDetail
achievementUid: learn.application-lifecycle-management-power-platform.trophy
metadata:
  title: >-
    Microsoft Trophy: Application lifecycle management for the Power Platform
    was issued by Microsoft
socialImageUrl: >-
  /training/achievements/application-lifecycle-management-power-platform-social.png
