### YamlMime:ModuleUnit 
uid: learn-bizapps.patient-access-service-center.4-configure-knowledge-articles 
title: Exercise - Create and manage knowledge articles
metadata: 
  title: Exercise - Create and manage knowledge articles
  description: Learn how to create and manage knowledge articles in the Patient Service Center.
  ms.date: 11/21/2023  
  author: AshokSudhaMCRSOFT 
  ms.author: sudhaashok 
  ms.topic: unit
durationInMinutes: 11 
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/4-configure-knowledge-articles.md)] 
