### YamlMime:ModuleUnit 
uid: learn-bizapps.modern-analytics-excel.3-types-security 
title: Dataset types and security
metadata: 
  title: Dataset types and security
  description: Learn about dataset types and security.
  ms.date: 09/28/2021 
  author: maggiesMSFT 
  manager: kfollis 
  ms.author: maggies 
  ms.topic: unit
durationInMinutes: 5 
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/3-types-security.md)] 
