### YamlMime:ModuleUnit 
uid: learn-bizapps.power-pages-extend.application-lifecycle 
title: Power Pages website life cycle management
metadata: 
  title: Power Pages website life cycle management
  description: Learn about the development life cycle and how to migrate solutions.
  ms.date: 05/26/2023
  author: DaveBeasley 
  ms.author: dbeasley 
  ms.topic: unit
durationInMinutes: 15
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/application-lifecycle.md)] 
