### YamlMime:ModuleUnit 
uid: learn-bizapps.unified-authoring-online-workshop.productivity-features 
title: Productivity features
metadata: 
  title: Productivity features
  description: Learn about productivity features.
  ms.date: 01/16/2024 
  author: DaveBeasley 
  ms.author: dbeasley 
  ms.topic: unit
durationInMinutes: 2 
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/productivity-features.md)] 
