### YamlMime:ModuleUnit 
uid: learn-bizapps.healthcare-care-management.3-navigate-application 
title: Exercise - Navigate the Care Management application
metadata: 
  title: Exercise - Navigate the Care Management application
  description: Follow the steps to learn how to navigate the Care Management application.
  ms.date: 10/30/2023   
  author: AshokSudhaMCRSOFT 
  ms.author: sudhaashok 
  ms.topic: unit
durationInMinutes: 8 
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/3-navigate-application.md)] 
