### YamlMime:ModuleUnit
uid: learn-bizapps.power-pages-studio-data-security.security
title: Power Pages security features
metadata:
  title: Power Pages security features
  description: Learn about using security features in Power Pages design studio.
  ms.date: 01/02/2024
  author: DaveBeasley
  ms.author: dbeasley
  ms.topic: unit
durationInMinutes: 3
content: |
 [!include[](../includes/unit-banner.md)]
 [!include[](includes/security.md)]
