### YamlMime:ModuleUnit 
uid: learn-bizapps.get-started-power-platform-app-makers.environments 
title: Introduction to environments
metadata: 
  title: Introduction to environments
  description: Learn about environments.
  ms.date: 12/13/2023 
  author: DaveBeasley 
  ms.author: dbeasley 
  ms.topic: unit 
durationInMinutes: 8 
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/environments.md)] 
