### YamlMime:ModuleUnit
uid: learn-bizapps.powerapps-common-data-service.logic-security
title: Dataverse logic and security
metadata:
  title: Dataverse logic and security
  description: Learn about apply logic and security to Dataverse tables.
  ms.date: 12/01/2023
  author: jadaphillips
  ms.author: jadaphillips
  ms.topic: unit
durationInMinutes: 6
content: |
 [!include[](../includes/unit-banner.md)]
 [!include[](includes/logic-security.md)]
