### YamlMime:ModuleUnit
uid: learn-bizapps.implement-power-virtual-agents.2-environments
title: Environments in Microsoft Copilot Studio
metadata:
  title: Environments in Microsoft Copilot Studio
  description: Learn how to create bots in different environments.
  ms.date: 10/02/2023
  author: jadaphillips
  ms.author: jadaphillips
  ms.topic: unit
durationInMinutes: 5
content: |
 [!include[](../includes/unit-banner.md)]
 [!include[](includes/2-environments.md)]
