### YamlMime:ModuleUnit
uid: learn-bizapps.azure-health-bot.3-configure-customer-service-omnichannel-chat
title: Set up Omnichannel for Customer Service live chat
metadata:
  title: Set up Omnichannel for Customer Service live chat
  description: Set up live chat for Omnichannel for Dynamics 365 Customer Service to connect and engage with customers across digital messaging channels.
  ms.date: 10/30/2023
  author: AshokSudhaMCRSOFT
  ms.author: sudhaashok
  ms.topic: unit
durationInMinutes: 25
content: |
 [!include[](../includes/unit-banner.md)]
 [!include[](includes/3-configure-customer-service-omnichannel-chat.md)]
