### YamlMime:ModuleUnit
uid: learn-bizapps.retail-store-operations-assist-teams-shifts.configure-integration
title: Exercise - Set up Shifts integration in Store Operations Assist
metadata:
  title: Exercise - Set up Shifts integration in Store Operations Assist
  description: Follow the steps to set up Shifts integration in Store Operations Assist.
  ms.date: 12/01/2023
  author: lavanyapg
  ms.author: lsuresh
  ms.topic: unit
durationInMinutes: 3
content: |
 [!include[](../includes/unit-banner.md)]
 [!include[](includes/configure-integration.md)]
