### YamlMime:ModuleUnit
uid: learn-bizapps.process-advisor-introduction.hyperautomation
title: Process Mining concepts and its role in hyperautomation 
metadata:
  title: Process Mining concepts and its role in hyperautomation 
  description: Learn about Process Mining concepts and its role in hyperautomation.
  ms.date: 04/02/2023
  author: DaveBeasley
  ms.author: dbeasley
  ms.topic: unit
durationInMinutes: 5
content: |
 [!include[](../includes/unit-banner.md)]
 [!include[](includes/hyperautomation.md)]
