### YamlMime:ModuleUnit 
uid: learn-bizapps.configure-custom-connectors-api.6-environments 
title: Share and move between environments
metadata: 
  title: Share and move between environments 
  description: Learn how to share and move between environments. 
  ms.date: 05/12/2023 
  author: DaveBeasley 
  ms.author: dbeasley 
  ms.topic: unit
  
durationInMinutes: 5
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/6-environments.md)] 
