### YamlMime:ModuleUnit
uid: learn-bizapps.wwl.introduction-power-apps.explore-canvas-applications
title: Explore canvas applications
metadata:
  title: Explore canvas applications
  description: "Introduction to canvas apps created in Microsoft Power Apps."
  ms.date: 02/20/2024
  author: wwlpublish
  ms.author: ceabrams
  ms.topic: unit
durationInMinutes: 7
content: |
  [!include[](includes/3-explore-canvas-applications.md)]