### YamlMime:ModuleUnit 
uid: learn-bizapps.intro-to-power-bi-mobile-apps.6-configure-app-settings
title: Configure app settings
metadata: 
  title:  Configure app settings
  description: Learn how to configure your Power BI Mobile app for increased security and ease of use. 
  ms.date: 06/24/2023 
  author: paulinbar
  manager: kfollis 
  ms.author: painbar 
  ms.topic: unit
   
durationInMinutes: 12 
content: |
  [!include[](../includes/unit-banner.md)]
  [!include[](includes/6-configure-app-settings.md)] 

