### YamlMime:ModuleUnit 
uid: learn-bizapps.power-bi-embedded-select.development-environment 
title: Set up a development environment
metadata: 
  title: Set up a development environment
  description: Learn how to set up a development environment.
  ms.date: 04/10/2022 
  author: KesemSharabi 
  manager: kfollis 
  ms.author: kesharab 
  ms.topic: unit
durationInMinutes: 5 
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/development-environment.md)] 
