### YamlMime:ModuleUnit 
uid: learn-bizapps.retail-set-up-store-operations-assist-teams.exercise-environment-variables 
title: Exercise – Set up environment variables for Store Operations Assist Teams
metadata: 
  title: Exercise – Set up environment variables for Store Operations Assist Teams
  description: Follow the steps to set up environment variables for Store Operations Assist Teams.
  ms.date: 10/04/2023
  author: lavanyapg 
  ms.author: lsuresh 
  ms.topic: interactive-tutorial 
  ms.service: microsoft-cloud-retail
durationInMinutes: 20 
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/exercise-environment-variables.md)] 
