### YamlMime:ModuleUnit 
uid: learn-bizapps.power-pages-authentication-user-management.authentication-settings 
title: Power Pages authentication settings
metadata: 
  title: Power Pages authentication settings
  description: Learn about authentication settings and categories in Power Pages.
  ms.date: 05/08/2023
  author: DaveBeasley 
  ms.author: dbeasley 
  ms.topic: unit
durationInMinutes: 10
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/authentication-settings.md)] 
