### YamlMime:ModuleUnit 
uid: learn-bizapps.policy-templates-custom-connectors.4-configure-host-url-routing 
title: Configure host URL and routing
metadata: 
  title: Configure host URL and routing 
  description: Learn how to configure host URL and routing. 
  ms.date: 05/12/2023 
  author: DaveBeasley 
  ms.author: dbeasley 
  ms.topic: unit
  
durationInMinutes: 3 
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/4-configure-host-url-routing.md)] 
