### YamlMime:ModuleUnit 
uid: learn-bizapps.policy-templates-custom-connectors.5-add-update-values 
title: Add or update values
metadata: 
  title: Add or update values  
  description: Learn how to add or update values.  
  ms.date: 05/12/2023 
  author: DaveBeasley 
  ms.author: dbeasley 
  ms.topic: unit
  
durationInMinutes: 4 
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/5-add-update-values.md)] 
