### YamlMime:ModuleUnit
uid: learn-bizapps.power-platform-architecture.2-environments
title: Environments
metadata:
  title: Environments
  description: Learn how environments are used in Power Platform.
  ms.date: 03/09/2023
  author: DaveBeasley
  ms.author: dbeasley 
  ms.topic: unit
durationInMinutes: 7
content: |
 [!include[](../includes/unit-banner.md)]
 [!include[](includes/2-environments.md)]
