### YamlMime:ModuleUnit 
uid: learn-bizapps.healthcare-interoperability-build-application.data-routes 
title: Data routing in virtual health data tables
metadata: 
  title: Data routing in virtual health data tables
  description: Learn how to use data routes in virtual health data tables.
  ms.date: 11/23/2023 
  author: AshokSudhaMCRSOFT 
  ms.author: sudhaashok 
  ms.topic: unit 
durationInMinutes: 5 
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/data-routes.md)] 
