### YamlMime:ModuleUnit
uid: learn-bizapps.power-pages-intro.security
title: Overview of Power Pages security
metadata:
  title: Overview of Power Pages security
  description: Learn about the basics of Power Pages security.
  ms.date: 01/04/2024
  author: DaveBeasley
  ms.author: dbeasley
  ms.topic: unit
durationInMinutes: 5
content: |
 [!include[](../includes/unit-banner.md)]
 [!include[](includes/security.md)]
