### YamlMime:ModuleUnit 
uid: learn-bizapps.power-apps-model-driven-apps-online-workshop.exercise-test-application 
title: Exercise - Test the application
metadata: 
  title: Exercise - Test the application
  description: Follow the steps to test the application.
  ms.date: 02/16/2024
  author: DaveBeasley 
  ms.author: dbeasley 
  ms.topic: unit
durationInMinutes: 10
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/exercise-test-application.md)] 
