### YamlMime:ModuleUnit
uid: learn-bizapps.security-governance-intro.2-environments
title: Identify Microsoft Power Platform environments
metadata:
  title: Identify Microsoft Power Platform environments
  description: Learn how to identify Microsoft Power Platform environments.
  ms.date: 10/02/2023
  author: DaveBeasley
  ms.author: dbeasley
  ms.topic: unit
durationInMinutes: 5
content: |
 [!include[](../includes/unit-banner.md)]
 [!include[](includes/2-environments.md)]
